:path: ../files/

= Step 7 - Create reception acknowledgement (RC4) [[s7]]

== Files [[s7-files]]

* link:{path}receipt-rc4.xml[receipt-rc4.xml] - Receipt RC4


== Documentation [[s7-doc]]

The RC4 contains this structure:

.Reception acknowledgement (RC4) structure
----
StandardBusinessDocument
+-- StandardBusinessDocumentHeader
+-- ReceptionAcknowledgement
----

The instance of `StandardBusinessDocumentHeader` is created similarly to the inner SBDH. Details are defined further below.

The instance of `ReceptionAcknowledgement` contains an `StandardBusinessDocumentHeader` to be identical to the `StandardBusinessDocumentHeader` received for which the receipt is created.


=== Transport identifiers in example

Sender:: `9908:810418052`

PPID identifies sender party, identical to the receiver party in the SBDH received.

Receiver:: `9908:991825827`

PPID identifies receiver party, identical to the sender party in the SBDH received.

// TODO
Document type identifier::  `urn:fdc:difi.no:2017:payment:extras-1::ReceptionAcknowledgement##urn:fdc:difi.no:2017:payment:handling:1.0:for:urn:iso:std:iso:20022:tech:xsd:pain.001.001.03:restricted:urn:fdc:bits.no:2017:iso20022:1.5::1.0`

Document type identifier as defined by Difi, follows pattern as defined by OpenPEPPOL.

.How to construct the document type identifier:
--
* Namespace of Payment Extras (`urn:fdc:difi.no:2017:payment:extras-1`)
* Separator (`::`)
* Document type (`ReceptionAcknowledgement`)
* Separator (`##`)
* Identifier for payment handling (`urn:fdc:difi.no:2017:payment:handling:1.0`)
* Separator (`:for:`)
* Namespace of received document (`urn:iso:std:iso:20022:tech:xsd:pain.001.001.03`)
* Separator (`:restricted:`)
* Customization of received document (`urn:fdc:bits.no:2017:iso20022:1.5`)
* Separator (`::`)
* Version of ReceptionAcknowledgement (`1.0`)
--

Process identifier:: `urn:fdc:bits.no:2017:profile:01:1.0`

Process identifier as defined by BITS/Difi.


=== Document identifiers in example

Standard:: `urn:fdc:difi.no:2017:payment:extras-1`

TypeVersion:: `1.0`

InstanceIdentifier:: `13bea627-5c12-42ff-a2c2-35540d279965`

UUID generated by the system creating RC4. Identifies the receipt.

Type:: `ReceptionAcknowledgement`

Time of creation:: `2017-05-05T22:02:00`

Defining time of creation of the receipt.


== References [[s7-ref]]

* link:https://github.com/difi/iso20022-extras[Payment Extras]

See *step 4* for futher references.


== Changelog [[s7-changelog]]

[cols="1,4", options="header"]
|===
| Date | Description
| 2017-05-13 | Initial version.
|===
