:path: ../files/

= Step 3 - Create inner SBDH [[s4]]


== Files [[s4-files]]

* link:{path}sbdh.xml[sbdh.xml] - Standard Business Document Header (Inner SBDH)


== Documentation [[s4-doc]]

The inner SBDH is created based upon the specification by OpenPEPPOL where references to UBL based document types are replaced by corresponding metadata for ISO 20022 document types as defined by BITS.

In this step is `StandardBusinessDocumentHeader` used as root element in the document, unlike as described in the specification by OpenPEPPOL. Such use is described in the SBDH standard.


=== Transport identifiers in example

Sender:: `9908:991825827`

PPID identifies sender party.

Receiver:: `9908:810418052`

PPID identifies receiver party.

Document type identifier::  `urn:iso:std:iso:20022:tech:xsd:pain.001.001.03::Document##urn:fdc:bits.no:2017:iso20022:1.5::03`

Document type identifier as defined by BITS/Difi, follows pattern as defined by OpenPEPPOL.

Process identifier:: `urn:fdc:bits.no:2017:profile:01:1.0`

Process identifier as defined by BITS/Difi.


=== Document identifiers in example

Standard:: `urn:iso:std:iso:20022:tech:xsd:pain.001.001.03`

Namespace defining the document type as provided by ISO 20022.

TypeVersion:: `03`

Version of the document type used. In the case of ISO 20022 is version given by the last two digits in the document type namespace.

InstanceIdentifier:: `13bea627-5c12-42ff-a2c2-35540d279965`

UUID generated by the sending system. Used to keep track of delivery status as this is reflected in RC4.

Type:: `Document`

Value `Document` is used for all ISO 20022 document types.

Time of creation:: `2017-05-05T22:00:00`

Defining time of creation of the inner SBDH.


== References [[s4-ref]]

* link:https://joinup.ec.europa.eu/svn/peppol/TransportInfrastructure/ICT-Transport-OpenPEPPOL-Envelope_Specification-100_2014-01-15.pdf[OpenPEPPOL Envelope Specification]
* link:https://joinup.ec.europa.eu/svn/peppol/TransportInfrastructure/PEPPOL_Policy%20for%20use%20of%20identifiers-300.pdf[OpenPEPPOL Policy for use of identifiers]
* link:https://en.wikipedia.org/wiki/ISO/IEC_6523[ISO/IEC 6523] (informal)
* link:http://www.gs1.org/docs/gs1_un-cefact_%20xml_%20profiles/CEFACT_SBDH_TS_version1.3.pdf[UN/CEFACT Standard Business Document Header 1.3]


== Changelog [[s4-changelog]]

[cols="1,4", options="header"]
|===
| Date | Description
| 2017-05-11 | Initial version.
|===
